export enum ViolationType {
  TAB_SWITCH = 'TAB_SWITCH',
  KEYBOARD_COPY = 'KEYBOARD_COPY',
  KEYBOARD_PASTE = 'KEYBOARD_PASTE',
  CAMERA_MULTIPLE_FACES = 'CAMERA_MULTIPLE_FACES',
  CAMERA_GAZE_AWAY = 'CAMERA_GAZE_AWAY',
  CAMERA_MISSING = 'CAMERA_MISSING',
  OTHER = 'OTHER',
}
